# TODO [x] remove link for year on post page
# TODO [x] add tag name to header on tag pages
# TODO [X] style the tag lists on the post page
# TODO [x] add subtitles to index page cards
# TODO [X] add iframes to slides page/posts page
# TODO [ ] fix all slides
# TODO [ ] add redirects to all pages
# TODO [ ] test redirects and compare links
# TODO [ ] add apps check if needed
# TODO [ ] fix all featured 
# TODO [x] fix index cards
# TODO [ ] clean up all titles, dates and subtitles to be the same
# TODO [x] clean up img folder remove all unused images
# TODO [ ] write missing posts
# TODO [ ] add alt text to all images
# TODO [ ] add description to all pages via site.description
# TODO [ ] add image to all pages via site.defaultimg


# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ZeroSpatial
subtitle:
description: "ZeroSpatial is a blog focusing on desktop and web-based geospatial applications. ZeroSpatial is maintained by Malcolm T Meyer."
keywords: ["gis", "blog", "geospatial", "vector tiles", "mapbox", "leaflet", "web maps", "dataviz"]
author: Malcolm T Meyer
language: en
timezone: America/New_York
defaultimage: "serving-vector-tiles.jpg"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: "https://zerospatial.com"
root: /
permalink: :category/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: blog
category_dir: categories
#code_dir: downloads/code
i18n_dir: :lang
skip_render: 
 - apps/**/*.*
 - apps-plugins/**
 - data/**/*.*
 - js/**/*.*
 - css/**/*.*
 - "**/*.js"

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page
archive: 6

# Category & Tag
default_category: blog
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D, YYYY
time_format: HH:mm:ss

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: chota-hero

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

include: 
 - _pages/**/*.*
 - slides/**/*.*
 
#Hexo Exceprt Plugin
excerpt:
  depth: 2
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true

#https://github.com/vseventer/hexo-imagemin - makes generating very slow
imagemin:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 7
  pngquant: false
  progressive: true

# More detailed settings
popularPosts:

  # (optional) Popular posts options
  # googleAnalyticsAPI:
  #   clientId: ******.apps.googleusercontent.com
  #   serviceEmail: *****@developer.gserviceaccount.com
  #   key: /hexo-project-root/path/to/google-services.pem
  #   viewId: 12345678
  #   dateRange: 30
  #   expiresDate: 10
  #   pvMeasurementsStartDate: 2015/11/01
  #   rankingSheet: rankingSheet.txt
    # cache:            # (Deprecated) This options is Deprecated > v0.1.3
    #  path: hexo-related-popular-posts-ga-cached.json  # (Deprecated) This options is Deprecated > v0.1.3
    #  expiresDate: 10  # (Deprecated) This options is Deprecated > v0.1.3
    
  # (optional) Advanced Related posts options
  # morphologicalAnalysis: 
  #   negativeKeywordsList: pluginSettings/hexo-rpp-negativewords.txt
  #   limit: 300
    
  # (optional) Related post's weight options
  weight:
    tagRelevancy: 1.0
    contentsRelevancy: 1.0
    
  # (optional) Cache options (Improve generation speed.)
  cache:
    path: .cache/hexo-popular-related-posts-ga-cached.json
    
  # (optional) Log options
  log: true